name: CI

on:
  push:
    branches: [main, master]
    paths-ignore:
      - 'playground/**'
  pull_request:
    branches: [main, master]
    paths-ignore:
      - 'playground/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm i -D playwright

      - name: Get browser version
        id: playwright-version
        run: echo "version=$(pnpm list playwright --json | jq -r '.[0].devDependencies.playwright.version')" >> $GITHUB_OUTPUT

      - name: Get cached browser version
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Install browser
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium --with-deps

      - name: Install browser deps only
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps chromium

      - run: pnpm build
